**`>>> 作者：东南有大树；公众号：大树投研。`**

---

### 本节概要

- 数组的创建
- 常用函数
- 数组的运算

### 数组的创建

In [1]:
# 导入numpy模块
import numpy as np
# 或者
# from numpy import *

In [15]:
# 创建数组
_array = np.array([1, 2, 3, 4])
_array
print(type(_array))

<class 'numpy.ndarray'>


In [23]:
# 创建数组
_array = np.array([[1, 2, 3, 4], 
                   [2, 3, 4, 5]])
_array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

### 常用函数与属性

In [19]:
# 查看行数
_array.ndim

2

In [5]:
# 查看数组形状
_array.shape

(2, 4)

In [24]:
# 查看元素类型
_array.dtype

dtype('int64')

In [25]:
# 创建全是0的数组
_array = np.zeros((5, 6))
_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
# 创建全是1的数组
_array = np.ones((5, 6))
_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
# 创建序列数组
_array = np.arange(0, 10, 2)
_array

array([0, 2, 4, 6, 8])

In [27]:
# 创建等差序列数组
_array = np.linspace(0, 10, 20)
_array

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
# 数组的索引
_array = np.array([[1, 2, 3, 4], 
                   [2, 3, 4, 5]])
print(_array[0])  # 第一行
print(_array[0][2])  # 第一行第3列
print(_array[:, 2])  # 所有的行与第有列
print(_array[-1][-1])  # 从后向前获取

[1 2 3 4]
3
[3 4]
5


### 数组的运算

In [35]:
# 数组运算
_array1 = np.array([1, 2, 3, 4])
_array2 = np.array([2, 3, 4, 5])
print('>>>\n', _array1 * 2)
print('>>>\n', _array1 + _array2)
print('>>>\n', _array2 > 3)
print('>>>\n', _array2.max())
print('>>>\n', _array2.min())
print('>>>\n', _array2.sum())

>>>
 [2 4 6 8]
>>>
 [3 5 7 9]
>>>
 [False False  True  True]
>>>
 5
>>>
 2
>>>
 14


---
关注“大树投研”公众号，回复关键字“入门指南”，获得与视频相关的文件、源代码等资料！